name: Receive Dispatch

on:
  repository_dispatch:
    types: [event_name]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip3 install requests && python3 parser.py ${{github.event.client_payload.repo_name}} ${{github.event.client_payload.release_version}}
          git config --global user.email "${{secrets.CI_EMAIL}}"
          git config --global user.name "${{secrets.CI_USERNAME}}"
          git pull
          git add .
          git commit -m "Generating sonarcloud metrics for ${{github.event.client_payload.repo_name}}"
          git push
          echo "Compile complete."