site_name: 2021.2 - SiGeD

repo_name: '2021-2-SiGeD-Doc'
repo_url: 'https://github.com/fga-eps-mds/2021-2-SiGeD-Doc'

lang:
  - pt

extra_javascript:
  - assets/js/extra.js

extra_css:
  - assets/css/docs.css

nav:
  - Home: index.md
  - Documentação:
    - Metodologia: metodologia.md
    - Documento de Arquitetura de Software: das.md
    - Gerenciamento de Equipe: equipe.md
    - Planejamento de Custo: planejamento_custo.md
    - EVM: evm.md
    - Gerenciamento de Riscos: planejamento_risco.md
    - Guia de estilo: guiadeestilo.md
    - Gerência de Configuração:
      - Políticas de contribuição: contribuicao.md
      - Pipelines de DevOps: pipelines.md
  - Reuniões:
    - Reunião 09/02 (Configuração): reunioes/09-02-config-eps.md
    - Reunião 09/02 (Treinamento): reunioes/09-02-treinamento.md
    - Reunião 16/02: reunioes/16-02-reuniao-cliente.md
    - Reunião 24/02: reunioes/24-02-reuniao-cliente.md
    - Reunião 02/03: reunioes/02-03-reuniao-sonarcloud.md
    - Reunião 03/03 (Usuários): reunioes/03-03-reuniao-clientes.md
    - Reunião 03/03 (Serviço Cargos): reunioes/03-03-reuniao-cargos.md
    - Reunião 04/03: reunioes/04-03-reuniao-extraordinaria.md
    - Reunião 06/03: reunioes/06-03-reuniao-pareamentos.md
    - Reunião 09/03: reunioes/09-03-reuniao-clientes.md
    - Reunião 10/03: reunioes/10-03-reuniao-extraordinaria.md
    - Reunião 11/03 (Deploy): reunioes/11-03-reuniao-extraordinaria-deploy.md
    - Reunião 11/03 (Usuários): reunioes/11-03-reuniao-extraordinaria.md

theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
