site_name: 2021.2 - SiGeD

repo_name: '2021-2-SiGeD-Doc'
repo_url: 'https://github.com/fga-eps-mds/2021-2-SiGeD-Doc'

lang:
  - pt

extra_javascript:
  - assets/js/extra.js

extra_css:
  - assets/css/docs.css

nav:
  - Home: index.md
  - Documentação:
    - Metodologia: metodologia.md
    - Documento de Arquitetura de Software: das.md
    - Gerenciamento de Equipe: equipe.md
    - Planejamento de Custo: planejamento_custo.md
    - Gerenciamento de Riscos: planejamento_risco.md
  - Lean Inception: visao_produto.md
  - Comunidade: contribuicao.md

theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/github